# Install Spark-HPC pre-requisite software packages
# NOTE: remote_user needs to be changed to the account
# name you use to connect to the machines where you will
# perform the install. This account needs to have sudo
# permissions.

---
- hosts: install_nodes
  connection: ssh
  become: yes
  remote_user: root
  vars:
    current_dir: ~/dependent-modules/

  tasks:

    - include: tasks/prereqs-install-debian.yml
      when: ansible_os_family == 'Debian'

    - include: tasks/prereqs-install-rhel.yml
      when: ansible_os_family == 'RedHat'
